
package fr.interop_fibre.wsdl.ftth.infotravaux.v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getInfoTravauxFTTHService", targetNamespace = "http://interop-fibre.fr/wsdl/ftth/infoTravaux/v1-0", wsdlLocation = "file:/home/jlesaux/workspace/infotravauxftth/infoTravauxFTTH/infoTravauxFTTH.wsdl")
public class GetInfoTravauxFTTHService_Service
    extends Service
{

    private final static URL GETINFOTRAVAUXFTTHSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETINFOTRAVAUXFTTHSERVICE_EXCEPTION;
    private final static QName GETINFOTRAVAUXFTTHSERVICE_QNAME = new QName("http://interop-fibre.fr/wsdl/ftth/infoTravaux/v1-0", "getInfoTravauxFTTHService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/jlesaux/workspace/infotravauxftth/infoTravauxFTTH/infoTravauxFTTH.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETINFOTRAVAUXFTTHSERVICE_WSDL_LOCATION = url;
        GETINFOTRAVAUXFTTHSERVICE_EXCEPTION = e;
    }

    public GetInfoTravauxFTTHService_Service() {
        super(__getWsdlLocation(), GETINFOTRAVAUXFTTHSERVICE_QNAME);
    }

    public GetInfoTravauxFTTHService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETINFOTRAVAUXFTTHSERVICE_QNAME, features);
    }

    public GetInfoTravauxFTTHService_Service(URL wsdlLocation) {
        super(wsdlLocation, GETINFOTRAVAUXFTTHSERVICE_QNAME);
    }

    public GetInfoTravauxFTTHService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETINFOTRAVAUXFTTHSERVICE_QNAME, features);
    }

    public GetInfoTravauxFTTHService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetInfoTravauxFTTHService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetInfoTravauxFTTHService
     */
    @WebEndpoint(name = "getInfoTravauxFTTHPort")
    public GetInfoTravauxFTTHService getGetInfoTravauxFTTHPort() {
        return super.getPort(new QName("http://interop-fibre.fr/wsdl/ftth/infoTravaux/v1-0", "getInfoTravauxFTTHPort"), GetInfoTravauxFTTHService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetInfoTravauxFTTHService
     */
    @WebEndpoint(name = "getInfoTravauxFTTHPort")
    public GetInfoTravauxFTTHService getGetInfoTravauxFTTHPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://interop-fibre.fr/wsdl/ftth/infoTravaux/v1-0", "getInfoTravauxFTTHPort"), GetInfoTravauxFTTHService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETINFOTRAVAUXFTTHSERVICE_EXCEPTION!= null) {
            throw GETINFOTRAVAUXFTTHSERVICE_EXCEPTION;
        }
        return GETINFOTRAVAUXFTTHSERVICE_WSDL_LOCATION;
    }

}
