
package fr.interop_fibre.wsdl.ftth.infotravaux.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "getInfoTravauxFTTHService", targetNamespace = "http://interop-fibre.fr/wsdl/ftth/infoTravaux/v1-0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetInfoTravauxFTTHService {


    /**
     * 
     * @param getInfoTravauxFTTHRequest
     * @return
     *     returns fr.interop_fibre.wsdl.ftth.infotravaux.v1_0.GetInfoTravauxFTTHOutput
     * @throws InfoFtthErrorMessage
     */
    @WebMethod(action = "getInfoTravauxFTTH")
    @WebResult(name = "getInfoTravauxFTTHResponse", targetNamespace = "http://interop-fibre.fr/wsdl/ftth/infoTravaux/v1-0", partName = "getInfoTravauxFTTHResponse")
    public GetInfoTravauxFTTHOutput getInfoTravauxFTTH(
        @WebParam(name = "getInfoTravauxFTTHRequest", targetNamespace = "http://interop-fibre.fr/wsdl/ftth/infoTravaux/v1-0", partName = "getInfoTravauxFTTHRequest")
        GetInfoTravauxFTTHInput getInfoTravauxFTTHRequest)
        throws InfoFtthErrorMessage
    ;

}
