
package fr.interop_fibre.wsdl.ftth.infotravaux.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "infoFtthError", targetNamespace = "http://interop-fibre.fr/wsdl/ftth/infoTravaux/v1-0")
public class InfoFtthErrorMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InfoFtthError faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InfoFtthErrorMessage(String message, InfoFtthError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InfoFtthErrorMessage(String message, InfoFtthError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.interop_fibre.wsdl.ftth.infotravaux.v1_0.InfoFtthError
     */
    public InfoFtthError getFaultInfo() {
        return faultInfo;
    }

}
